### ISSUE TITLE
Conversion functions should return numeric values

### ISSUE THREAD

**Issue by cclauss** [coomlata1/pythonista-scripts#21]
These four functions should return **numeric** values.  The format strings should be moved into the multiline formatting strings where these values are used.

``` python
precip_inch(mm)  # should it be renamed to mm_to_inches() ?
wind_mph(mps)  # should it be renamed to m_per_sec_to_mph() ?
wind_chill(temp,wind)
pressure_inhg(hPa)  # should it be renamed to hPa_to_inches() ?
```

**Comment by cclauss** [comment]
Also, do we want to support both Metric and Imperial or is Imperial only sufficient?

**Comment by coomlata1** [comment]
Probably support both for wide user base but the wind chill function and
string formatting will need to support metric.
