### ISSUE TITLE
Why do we eliminate the precip_type?

### ISSUE THREAD

**Issue by cclauss** [coomlata1/pythonista-scripts#25]
`If precip_type not in ('Rain', 'Snow', 'Clouds'):` then we eliminate it with lines 268 and 269:

``` python
  else:
    precip_type=''
```

What if it is 'Sleet’ or 'Sand Storms'?  Why not pass the value thru unprocessed?

**Comment by coomlata1** [comment]
In all the tests I've done on multiple cities all I get are rain, snow, clouds, and clear.  I've yet to see sleet, hail, etc.  Seems like a lot of redundancy to see a weather description and a weather type that repeat themselves.,

**Comment by coomlata1** [comment]
I put the the precip type back in.  You make a good point.  I might be overthinking this. Just pass the type and see what it brings if we get extreme weather like hurricane, tornado, etc.
